# format="$python$nodejs$all$character"
add_newline = true

# format="$all$directory$character"
# format = """
# [â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€>](bold green)
# [â”‚](bold green)$all
# [â””â”€>](bold green) $character"""

[character]                            # The name of the module we are configuring is "character"
success_symbol = "[\\$](bold green)" 


[directory]
# truncate_to_repo = false

[python]
# format="[$symbol($version )]($style)"

# [git_branch]
# format="[$symbol$branch]($style) "

[nodejs]
# format="[$symbol($version )]($style)"
# symbol="ğŸŸ¢ "

[gcloud]
format="on [$symbol$project]($style) "
# symbol="â˜ï¸ "
